version: "3.3"

services:
  jira_software:
    image: cptactionhank/atlassian-jira-software:7.12.3
    volumes:
      - ${SOFTWARE_PATH}:/var/atlassian/jira
      - ${SOFTWARE_PATH}/conf/server.xml:/opt/atlassian/jira/conf/server.xml
      - ${SOFTWARE_PATH}/atlassian-extras-3.2.jar:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/atlassian-extras-3.2.jar
    environment:
      - VIRTUAL_HOST=${SOFTWARE_HOST}
      - VIRTUAL_PORT=8080
  confluence:
    image: cptactionhank/atlassian-confluence:6.14.1
    volumes:
      - ${CONFLUENCE_PATH}:/var/atlassian/confluence
      - ${CONFLUENCE_PATH}/conf/server.xml:/opt/atlassian/confluence/conf/server.xml
    environment:
      - VIRTUAL_HOST=${CONFLUENCE_HOST}
      - VIRTUAL_PORT=8090
  # jira_servicedesk:

# docker network create --driver=bridge --subnet=10.50.0.0/16 baffedu
networks:
  default:
    external:
      name: baffedu