version: "3.3"

services:
  master:
    image: cptactionhank/atlassian-jira:latest
    environment:
      - VIRTUAL_HOST=${MASTER_HOST}
      - VIRTUAL_PORT=8080

# docker network create --driver=bridge --subnet=10.50.0.0/16 baffedu
networks:
  default:
    external:
      name: baffedu